# Generated by Django 5.1.1 on 2024-10-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/default_avatar.jpg', upload_to='avatars/'),
        ),
    ]
